name: money_track
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc:
  equatable:
  local_auth:
  flutter_credit_card:
  image_picker:
  share: ^2.0.4
  screenshot: ^1.2.3
  path_provider: ^2.0.9

  feature_discovery: ^0.14.1
  connectivity_plus: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true